/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Time = IDL.Int;
export const JobListing = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'jobType' : IDL.Text,
  'createdAt' : Time,
  'description' : IDL.Text,
  'isActive' : IDL.Bool,
  'department' : IDL.Text,
  'requirements' : IDL.Vec(IDL.Text),
  'location' : IDL.Text,
});
export const ProductListing = IDL.Record({
  'id' : IDL.Nat,
  'features' : IDL.Vec(IDL.Text),
  'name' : IDL.Text,
  'createdAt' : Time,
  'description' : IDL.Text,
  'isActive' : IDL.Bool,
  'price' : IDL.Text,
});
export const ContentBlock = IDL.Record({
  'key' : IDL.Text,
  'title' : IDL.Text,
  'content' : IDL.Text,
  'updatedAt' : Time,
});
export const ContactSubmission = IDL.Record({
  'id' : IDL.Nat,
  'subject' : IDL.Text,
  'name' : IDL.Text,
  'createdAt' : Time,
  'email' : IDL.Text,
  'message' : IDL.Text,
  'phone' : IDL.Text,
});

export const idlService = IDL.Service({
  'createJobListing' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Vec(IDL.Text)],
      [IDL.Nat],
      [],
    ),
  'createProductListing' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Vec(IDL.Text), IDL.Text],
      [IDL.Nat],
      [],
    ),
  'deleteJobListing' : IDL.Func([IDL.Nat], [], []),
  'deleteProductListing' : IDL.Func([IDL.Nat], [], []),
  'getActiveJobListings' : IDL.Func([], [IDL.Vec(JobListing)], ['query']),
  'getActiveProductListings' : IDL.Func(
      [],
      [IDL.Vec(ProductListing)],
      ['query'],
    ),
  'getAllContentBlocks' : IDL.Func([], [IDL.Vec(ContentBlock)], ['query']),
  'getAllJobListings' : IDL.Func([], [IDL.Vec(JobListing)], ['query']),
  'getAllProductListings' : IDL.Func([], [IDL.Vec(ProductListing)], ['query']),
  'getContactSubmissions' : IDL.Func(
      [],
      [IDL.Vec(ContactSubmission)],
      ['query'],
    ),
  'getContentBlock' : IDL.Func([IDL.Text], [IDL.Opt(ContentBlock)], ['query']),
  'seedDefaultContent' : IDL.Func([], [], []),
  'submitContactForm' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [],
      [],
    ),
  'updateContentBlock' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
  'updateJobListing' : IDL.Func(
      [
        IDL.Nat,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Vec(IDL.Text),
        IDL.Bool,
      ],
      [],
      [],
    ),
  'updateProductListing' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Text, IDL.Vec(IDL.Text), IDL.Text, IDL.Bool],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Time = IDL.Int;
  const JobListing = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'jobType' : IDL.Text,
    'createdAt' : Time,
    'description' : IDL.Text,
    'isActive' : IDL.Bool,
    'department' : IDL.Text,
    'requirements' : IDL.Vec(IDL.Text),
    'location' : IDL.Text,
  });
  const ProductListing = IDL.Record({
    'id' : IDL.Nat,
    'features' : IDL.Vec(IDL.Text),
    'name' : IDL.Text,
    'createdAt' : Time,
    'description' : IDL.Text,
    'isActive' : IDL.Bool,
    'price' : IDL.Text,
  });
  const ContentBlock = IDL.Record({
    'key' : IDL.Text,
    'title' : IDL.Text,
    'content' : IDL.Text,
    'updatedAt' : Time,
  });
  const ContactSubmission = IDL.Record({
    'id' : IDL.Nat,
    'subject' : IDL.Text,
    'name' : IDL.Text,
    'createdAt' : Time,
    'email' : IDL.Text,
    'message' : IDL.Text,
    'phone' : IDL.Text,
  });
  
  return IDL.Service({
    'createJobListing' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Vec(IDL.Text)],
        [IDL.Nat],
        [],
      ),
    'createProductListing' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Vec(IDL.Text), IDL.Text],
        [IDL.Nat],
        [],
      ),
    'deleteJobListing' : IDL.Func([IDL.Nat], [], []),
    'deleteProductListing' : IDL.Func([IDL.Nat], [], []),
    'getActiveJobListings' : IDL.Func([], [IDL.Vec(JobListing)], ['query']),
    'getActiveProductListings' : IDL.Func(
        [],
        [IDL.Vec(ProductListing)],
        ['query'],
      ),
    'getAllContentBlocks' : IDL.Func([], [IDL.Vec(ContentBlock)], ['query']),
    'getAllJobListings' : IDL.Func([], [IDL.Vec(JobListing)], ['query']),
    'getAllProductListings' : IDL.Func(
        [],
        [IDL.Vec(ProductListing)],
        ['query'],
      ),
    'getContactSubmissions' : IDL.Func(
        [],
        [IDL.Vec(ContactSubmission)],
        ['query'],
      ),
    'getContentBlock' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(ContentBlock)],
        ['query'],
      ),
    'seedDefaultContent' : IDL.Func([], [], []),
    'submitContactForm' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [],
        [],
      ),
    'updateContentBlock' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
    'updateJobListing' : IDL.Func(
        [
          IDL.Nat,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Vec(IDL.Text),
          IDL.Bool,
        ],
        [],
        [],
      ),
    'updateProductListing' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Text, IDL.Vec(IDL.Text), IDL.Text, IDL.Bool],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };