/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface ContactSubmission {
  'id' : bigint,
  'subject' : string,
  'name' : string,
  'createdAt' : Time,
  'email' : string,
  'message' : string,
  'phone' : string,
}
export interface ContentBlock {
  'key' : string,
  'title' : string,
  'content' : string,
  'updatedAt' : Time,
}
export interface JobListing {
  'id' : bigint,
  'title' : string,
  'jobType' : string,
  'createdAt' : Time,
  'description' : string,
  'isActive' : boolean,
  'department' : string,
  'requirements' : Array<string>,
  'location' : string,
}
export interface ProductListing {
  'id' : bigint,
  'features' : Array<string>,
  'name' : string,
  'createdAt' : Time,
  'description' : string,
  'isActive' : boolean,
  'price' : string,
}
export type Time = bigint;
export interface _SERVICE {
  'createJobListing' : ActorMethod<
    [string, string, string, string, string, Array<string>],
    bigint
  >,
  'createProductListing' : ActorMethod<
    [string, string, Array<string>, string],
    bigint
  >,
  'deleteJobListing' : ActorMethod<[bigint], undefined>,
  'deleteProductListing' : ActorMethod<[bigint], undefined>,
  'getActiveJobListings' : ActorMethod<[], Array<JobListing>>,
  'getActiveProductListings' : ActorMethod<[], Array<ProductListing>>,
  'getAllContentBlocks' : ActorMethod<[], Array<ContentBlock>>,
  'getAllJobListings' : ActorMethod<[], Array<JobListing>>,
  'getAllProductListings' : ActorMethod<[], Array<ProductListing>>,
  'getContactSubmissions' : ActorMethod<[], Array<ContactSubmission>>,
  'getContentBlock' : ActorMethod<[string], [] | [ContentBlock]>,
  'seedDefaultContent' : ActorMethod<[], undefined>,
  'submitContactForm' : ActorMethod<
    [string, string, string, string, string],
    undefined
  >,
  'updateContentBlock' : ActorMethod<[string, string, string], undefined>,
  'updateJobListing' : ActorMethod<
    [bigint, string, string, string, string, string, Array<string>, boolean],
    undefined
  >,
  'updateProductListing' : ActorMethod<
    [bigint, string, string, Array<string>, string, boolean],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];